; CanSat Skyline FSW — PlatformIO config
; Board: Heltec WiFi LoRa 32 V2

[env:heltec_wifi_lora_32_V2]
platform  = espressif32
board     = heltec_wifi_lora_32_V2
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit AMG88xx Library @ ^1.1.4
    adafruit/Adafruit INA219 @ ^1.2.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    sandeepmistry/LoRa @ ^0.8.0
    madhephaestus/ESP32Servo @ ^3.0.5